services:
  - type: web
    name: telegram-qr-bot
    runtime: python
    pythonVersion: 3.10.12
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: 8421221057:AAEtH6tnDHXG5EohTvysSZl5Pnp_mkKMl_A
